# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
exclude: [node_modules, dist, .sass-cache, .cache, .vscode, .babel.config.js, postcss.config.js, package.json, package-lock.json, Gemfile, Gemfile.lock, bsabel.config.js, brocfile.js, babel.config.js]
title: Advanced Macros
favicon: /favicon-32x32.png
# email: 
description: >-
  A mod to automate the player completely with both simple and complex macros scripts.
baseurl: "/" # the subpath of your site, e.g. /blog
repository: "https://github.com/AdvancedMacros/AdvancedMacros.github.io"
url: "https://AdvancedMacros.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title
locale: 'en'
lang: en

# twitter_username: jekyllrb
github_username:  AdvancedMacros
twitter:
  # username: 
  card: summary
logo: _favicons\apple-touch-icon.png

social:
  name: Advanced Macros
  links:
    # - https://twitter.com/
    - https://github.com/AdvancedMacros

include:
  - _redirects


author:
  # twitter: 
  github: AdvancedMacros
  name: Advanced Macros

# google_analytics: UA-114742711-1
# Build settings
markdown: kramdown
# markdown: CommonMark
# commonmark:
#   options: ["SMART", "FOOTNOTES", "UNSAFE", "HARDBREAKS", "LIBERAL_HTML_TAG", "STRIKETHROUGH_DOUBLE_TILDE"]
#   extensions: ["strikethrough", "autolink", "table"]
# theme: minima
plugins:
  - jekyll-archives
collections:
  # authors:
  #   output: true
  favicons:
    permalink: /:path/:name
  root_files:
    permalink: /:path/:name

defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true


highlighter: rouge
encoding: utf-8

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
